import type { StudioComposerDockProps } from "./studioComposerDockTypes";

export type StudioComposerToolbarProps = Pick<
  StudioComposerDockProps,
  | "activeComposerMenu"
  | "activeTemplateId"
  | "aspectRatioOptions"
  | "availableProviderCount"
  | "composerToolbarRef"
  | "customTemplates"
  | "editingTemplateId"
  | "hasActiveProject"
  | "providerGroups"
  | "resolutionOptions"
  | "selectedProvider"
  | "selectedGrokSkuLabel"
  | "selectedProviderModelName"
  | "selectedResolutionLabel"
  | "sharedTemplates"
  | "studioForm"
  | "submitting"
  | "submissionProgress"
  | "templateDraftLabel"
  | "templateDraftTitle"
  | "templateFeedback"
  | "uploadingReference"
  | "onApplyTemplate"
  | "onAspectRatioSelect"
  | "onCancelTemplateEdit"
  | "onDeleteCustomTemplate"
  | "onEditCustomTemplate"
  | "onGrokVideoSkuSelect"
  | "onImageCountSelect"
  | "onProviderSelect"
  | "onResolutionSelect"
  | "onSaveCustomTemplate"
  | "onTemplateDraftLabelChange"
  | "onTemplateDraftTitleChange"
  | "onToggleComposerMenu"
>;

export type StudioComposerToolbarMenusProps = Pick<
  StudioComposerToolbarProps,
  | "activeComposerMenu"
  | "activeTemplateId"
  | "aspectRatioOptions"
  | "customTemplates"
  | "editingTemplateId"
  | "providerGroups"
  | "resolutionOptions"
  | "selectedProvider"
  | "selectedGrokSkuLabel"
  | "selectedProviderModelName"
  | "selectedResolutionLabel"
  | "sharedTemplates"
  | "studioForm"
  | "templateDraftLabel"
  | "templateDraftTitle"
  | "templateFeedback"
  | "onApplyTemplate"
  | "onAspectRatioSelect"
  | "onCancelTemplateEdit"
  | "onDeleteCustomTemplate"
  | "onEditCustomTemplate"
  | "onGrokVideoSkuSelect"
  | "onImageCountSelect"
  | "onProviderSelect"
  | "onResolutionSelect"
  | "onSaveCustomTemplate"
  | "onTemplateDraftLabelChange"
  | "onTemplateDraftTitleChange"
  | "onToggleComposerMenu"
>;