from __future__ import annotations

import hashlib
import logging
import mimetypes
from pathlib import Path
from urllib.error import HTTPError, URLError
from urllib.parse import urlparse
from urllib.request import Request, urlopen

from app.services.media_storage import write_binary_asset, write_preview_svg

logger = logging.getLogger(__name__)

_BROWSER_UA = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36"
)


def _safe_slug(value: str, *, fallback: str = "inspiration") -> str:
    slug = "".join(char.lower() if char.isalnum() else "-" for char in value).strip("-")
    while "--" in slug:
        slug = slug.replace("--", "-")
    return slug[:80] or fallback


def _extension_for_downloaded_image(image_url: str, content_type: str | None, fallback: str) -> str:
    if content_type:
        guessed = mimetypes.guess_extension(content_type.split(";", 1)[0].strip().lower(), strict=False)
        if guessed:
            extension = guessed.lstrip(".")
            return "jpeg" if extension == "jpg" else extension

    suffix = Path(urlparse(image_url).path).suffix.lower().lstrip(".")
    if suffix:
        return "jpeg" if suffix == "jpg" else suffix

    normalized = fallback.lower().strip() or "png"
    return "jpeg" if normalized == "jpg" else normalized


def _download_remote_image(image_url: str, *, referer: str = "", timeout_seconds: float = 20.0) -> tuple[bytes, str | None]:
    request = Request(
        image_url,
        headers={
            "User-Agent": _BROWSER_UA,
            "Referer": referer or image_url,
        },
    )
    try:
        with urlopen(request, timeout=timeout_seconds) as response:
            payload = response.read()
            content_type = None
            if hasattr(response, "headers") and response.headers is not None:
                content_type = response.headers.get("Content-Type")
            return payload, content_type
    except HTTPError as exc:
        detail = exc.read().decode("utf-8", errors="ignore")
        raise ValueError(f"Image download failed with HTTP {exc.code}: {detail}") from exc
    except URLError as exc:
        raise ValueError(f"Image download failed: {exc.reason}") from exc


def _placeholder_path(title: str, namespace: str, source_key: str) -> str:
    slug = _safe_slug(title, fallback="untitled")
    digest = hashlib.sha1(source_key.encode("utf-8")).hexdigest()[:12]
    return f"inspiration/{namespace}/{slug}-{digest}.svg"


def _downloaded_image_path(title: str, namespace: str, image_url: str, content_type: str | None) -> str:
    slug = _safe_slug(title, fallback="untitled")
    digest = hashlib.sha1(image_url.encode("utf-8")).hexdigest()[:12]
    extension = _extension_for_downloaded_image(image_url, content_type, "png")
    return f"inspiration/{namespace}/{slug}-{digest}.{extension}"


def prepare_inspiration_image(
    image_path: str,
    *,
    title: str,
    source_url: str = "",
    namespace: str = "external",
) -> str:
    normalized = (image_path or "").strip()
    if not normalized:
        return write_preview_svg(
            _placeholder_path(title, namespace, f"{title}:{source_url}"),
            title=title,
            eyebrow="inspiration placeholder",
            detail="source image unavailable; fallback preview generated by QMDH",
            accent_seed=f"inspiration-placeholder:{title}:{source_url}",
            overwrite=False,
        )

    parsed = urlparse(normalized)
    if parsed.scheme not in {"http", "https"}:
        return normalized

    try:
        image_bytes, content_type = _download_remote_image(normalized, referer=source_url)
        return write_binary_asset(
            _downloaded_image_path(title, namespace, normalized, content_type),
            image_bytes,
            overwrite=False,
        )
    except Exception as exc:
        logger.warning("Failed to localize inspiration image %s for %s: %s", normalized, title, exc)
        return write_preview_svg(
            _placeholder_path(title, namespace, normalized),
            title=title,
            eyebrow="inspiration fallback",
            detail="source image unavailable; imported as managed fallback preview",
            accent_seed=f"inspiration-fallback:{normalized}",
            overwrite=False,
        )
